name: flameblasterfaster
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flame: ^1.8.0
  flame_audio: ^2.0.4
  logging: ^1.0.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/audio/explosion.wav
    - assets/audio/hit_enemy.wav
    - assets/audio/hit_ship.wav
    - assets/audio/laser_enemy.wav
    - assets/audio/laser_ship.wav
    - assets/audio/music.ogg
    - assets/audio/music.mp3
    - assets/audio/powerup.wav
    - assets/images/armor.png
    - assets/images/button_hover.png
    - assets/images/button_normal.png
    - assets/images/button_pressed.png
    - assets/images/enemy_clever.png
    - assets/images/enemy_kamikaze.png
    - assets/images/explosion.png
    - assets/images/flare.png
    - assets/images/laser_enemy.png
    - assets/images/laser_ship.png
    - assets/images/powerup_armor.png
    - assets/images/powerup_laser.png
    - assets/images/score.png
    - assets/images/ship.png
    - assets/images/smoke.png
    - assets/images/stars_close.png
    - assets/images/stars_far.png

  fonts:
    - family: m5x7
      fonts:
        - asset: assets/fonts/m5x7.ttf
